/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SansTarifRouteImport } from './routes/sans-tarif'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiUpdateMediaKitRouteImport } from './routes/api/update-media-kit'
import { Route as ApiMediaKitContentRouteImport } from './routes/api/media-kit-content'
import { Route as ApiCheckAdminCodeRouteImport } from './routes/api/check-admin-code'
import { Route as AdminConfigDotymlRouteImport } from './routes/admin/config[.]yml'

const SansTarifRoute = SansTarifRouteImport.update({
  id: '/sans-tarif',
  path: '/sans-tarif',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateMediaKitRoute = ApiUpdateMediaKitRouteImport.update({
  id: '/api/update-media-kit',
  path: '/api/update-media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaKitContentRoute = ApiMediaKitContentRouteImport.update({
  id: '/api/media-kit-content',
  path: '/api/media-kit-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckAdminCodeRoute = ApiCheckAdminCodeRouteImport.update({
  id: '/api/check-admin-code',
  path: '/api/check-admin-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigDotymlRoute = AdminConfigDotymlRouteImport.update({
  id: '/admin/config.yml',
  path: '/admin/config.yml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/partenaires': typeof PartenairesRoute
  '/sans-tarif': typeof SansTarifRoute
  '/admin/config.yml': typeof AdminConfigDotymlRoute
  '/api/check-admin-code': typeof ApiCheckAdminCodeRoute
  '/api/media-kit-content': typeof ApiMediaKitContentRoute
  '/api/update-media-kit': typeof ApiUpdateMediaKitRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/partenaires': typeof PartenairesRoute
  '/sans-tarif': typeof SansTarifRoute
  '/admin/config.yml': typeof AdminConfigDotymlRoute
  '/api/check-admin-code': typeof ApiCheckAdminCodeRoute
  '/api/media-kit-content': typeof ApiMediaKitContentRoute
  '/api/update-media-kit': typeof ApiUpdateMediaKitRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/partenaires': typeof PartenairesRoute
  '/sans-tarif': typeof SansTarifRoute
  '/admin/config.yml': typeof AdminConfigDotymlRoute
  '/api/check-admin-code': typeof ApiCheckAdminCodeRoute
  '/api/media-kit-content': typeof ApiMediaKitContentRoute
  '/api/update-media-kit': typeof ApiUpdateMediaKitRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/partenaires'
    | '/sans-tarif'
    | '/admin/config.yml'
    | '/api/check-admin-code'
    | '/api/media-kit-content'
    | '/api/update-media-kit'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/partenaires'
    | '/sans-tarif'
    | '/admin/config.yml'
    | '/api/check-admin-code'
    | '/api/media-kit-content'
    | '/api/update-media-kit'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/partenaires'
    | '/sans-tarif'
    | '/admin/config.yml'
    | '/api/check-admin-code'
    | '/api/media-kit-content'
    | '/api/update-media-kit'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartenairesRoute: typeof PartenairesRoute
  SansTarifRoute: typeof SansTarifRoute
  AdminConfigDotymlRoute: typeof AdminConfigDotymlRoute
  ApiCheckAdminCodeRoute: typeof ApiCheckAdminCodeRoute
  ApiMediaKitContentRoute: typeof ApiMediaKitContentRoute
  ApiUpdateMediaKitRoute: typeof ApiUpdateMediaKitRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sans-tarif': {
      id: '/sans-tarif'
      path: '/sans-tarif'
      fullPath: '/sans-tarif'
      preLoaderRoute: typeof SansTarifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-media-kit': {
      id: '/api/update-media-kit'
      path: '/api/update-media-kit'
      fullPath: '/api/update-media-kit'
      preLoaderRoute: typeof ApiUpdateMediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-kit-content': {
      id: '/api/media-kit-content'
      path: '/api/media-kit-content'
      fullPath: '/api/media-kit-content'
      preLoaderRoute: typeof ApiMediaKitContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-admin-code': {
      id: '/api/check-admin-code'
      path: '/api/check-admin-code'
      fullPath: '/api/check-admin-code'
      preLoaderRoute: typeof ApiCheckAdminCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config.yml': {
      id: '/admin/config.yml'
      path: '/admin/config.yml'
      fullPath: '/admin/config.yml'
      preLoaderRoute: typeof AdminConfigDotymlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartenairesRoute: PartenairesRoute,
  SansTarifRoute: SansTarifRoute,
  AdminConfigDotymlRoute: AdminConfigDotymlRoute,
  ApiCheckAdminCodeRoute: ApiCheckAdminCodeRoute,
  ApiMediaKitContentRoute: ApiMediaKitContentRoute,
  ApiUpdateMediaKitRoute: ApiUpdateMediaKitRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
